name: Wake Supabase

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Curl Supabase File
        run: |
          curl -s --fail \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            "${{secrets.SUPABASE_WAKE_URL}}" || exit 1
